In [1]:
# 1
import numpy as np
height =  [72,78, 69,71,76, 79]
height_np = np.array(height)

mean = np.mean(height_np)
std = np.std(height_np)

height_m = height_np - mean
height_s = height_m / std

print(height_s )

[-0.5831297   1.031691   -1.39054004 -0.85226648  0.49341743  1.30082778]


In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
attr = boston.data # attributes that may affact median values
medV = boston.target # median value
print(boston.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [3]:
print( boston.DESCR )

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [4]:
# 2.1
print(attr[9])

[1.7004e-01 1.2500e+01 7.8700e+00 0.0000e+00 5.2400e-01 6.0040e+00
 8.5900e+01 6.5921e+00 5.0000e+00 3.1100e+02 1.5200e+01 3.8671e+02
 1.7100e+01]


In [5]:
# 2.2
print(attr[19,5])

5.727


In [6]:
# 2.3
print(attr[medV < 6])

[[ 38.3518   0.      18.1      0.       0.693    5.453  100.       1.4896
   24.     666.      20.2    396.9     30.59  ]
 [ 25.0461   0.      18.1      0.       0.693    5.987  100.       1.5888
   24.     666.      20.2    396.9     26.77  ]
 [ 67.9208   0.      18.1      0.       0.693    5.683  100.       1.4254
   24.     666.      20.2    384.97    22.98  ]]


In [7]:
# 2.4
print(np.mean(attr[medV < 20,10]))

19.485238095238092


In [8]:
# 2.5
index = [2,9,12]
print(attr[:5,index])

[[  2.31 296.     4.98]
 [  7.07 242.     9.14]
 [  7.07 242.     4.03]
 [  2.18 222.     2.94]
 [  2.18 222.     5.33]]


In [9]:
# 3
def my_f(a):
    x = np.array(a)
    y = 6*x**2 + 2
    return y

y = my_f( [1,3,5] )
print(y)

[  8  56 152]
